[package]
authors = ["Max Inden <mail@max-inden.de>"]
description = "The Rust SDK for developing Testground test plans."
documentation = "https://docs.rs/testground"
edition = "2021"
license = "Apache-2.0 OR MIT"
name = "testground"
repository = "https://github.com/testground/sdk-rust/"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
durationfmt = { git = "https://github.com/kdar/durationfmt-rs.git" }
futures = { version = "0.3", default-features = false, features = [] }
futures-util = { version = "0.3", default-features = false, features = [] }
pnet = { version = "0.29", default-features = false, features = [] }
soketto = { version = "0.7", default-features = false, features = [] }
serde = { version = "1", default-features = false, features = ["derive"] }
serde_json = { version = "1", default-features = false, features = ["std"] }
serde_with = { version = "1", default-features = false, features = [] }
structopt = { version = "0.3", default-features = false, features = [] }
thiserror = { version = "1", default-features = false, features = [] }
tokio = { version = "1", default-features = false, features = ["sync", "rt-multi-thread", "macros", "net"] }
tokio-stream = { version = "0.1", default-features = false, features = [] }
tokio-util = { version = "0.6", default-features = false, features = ["compat"] }